### ISSUE TITLE
Trying to run evaluate-model on a folder of saliency maps for mit300

### ISSUE THREAD

**Issue by divyam28** [matthias-k/saliency-benchmarking#1]
```
Loading dataset mit300
Traceback (most recent call last):
  File "evaluate.py", line 545, in <module>
    cli()
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "evaluate.py", line 125, in evaluate_model
    _evaluate_model(dataset, type, output, evaluation, model_location)
  File "evaluate.py", line 140, in _evaluate_model
    benchmark = MIT300()
  File "C:\Users\Divyam Khanna\Desktop\Spring'21\DSCI552\Project\Final\benchmark\saliency-benchmarking\saliency_benchmarking\evaluation.py", line 146, in __init__
    super(MIT300, self).__init__(stimuli, fixations, saliency_map_provider, remove_doublicates=remove_doublicates, antonio_gaussian=antonio_gaussian, empirical_maps=empirical_maps)
  File "C:\Users\Divyam Khanna\Desktop\Spring'21\DSCI552\Project\Final\benchmark\saliency-benchmarking\saliency_benchmarking\evaluation.py", line 53, in __init__
    self.empirical_maps = pysaliency.FixationMap(stimuli, fixations, kernel_size=23.99, caching=cache_empirical_maps)
  File "C:\Users\Divyam Khanna\anaconda3\lib\site-packages\pysaliency\saliency_map_models.py", line 833, in __init__
    f = fixations[fixations.n == n]
AttributeError: 'FileStimuli' object has no attribute 'n'
```

**Comment by matthias-k** [comment]
Not sure where that error comes from, but for MIT300 you would need the ground truth data which is not public.
